### ISSUE TITLE
Need tutorial to get the video url

### ISSUE THREAD

**Issue by aalfiann** [japnimedev/Facebook-Stream-Player#1]
This is first time I try to use facebook video stream. but how to get the url video from facebook? is there any tutorial?

**Comment by japnimedev** [comment]
@aalfiann video link example `https://www.facebook.com/KaroshiMyriad/videos/1639101296112644/`
The url needs to be public; example image
![untitled](https://user-images.githubusercontent.com/29234610/33935266-39a99f64-e036-11e7-8500-835e8c6df9cc.png)

**Comment by aalfiann** [comment]
@japnimedev Thanks, it works perfectly..

Just curious, is it possible to upload long duration video like movie into facebook?

**Comment by japnimedev** [comment]
@aalfiann yup

**Comment by aalfiann** [comment]
can't waiting for the release to support private video...

**Comment by japnimedev** [comment]
Closed for the new updates.
