### ISSUE TITLE
how to adding défferent link plz 

### ISSUE THREAD

**Issue by audin213** [japnimedev/Facebook-Stream-Player#3]
hi thanks for this script but we need to insert link in directly in embed.php

how i can make it auto please ? i want say how i can use it with multi link another time

and hope the private video func its added soon

**Comment by japnimedev** [comment]
Dont worry, I'll update this script as soon as possible.

**Comment by audin213** [comment]
@japnimedev ok bro good luck

**Comment by japnimedev** [comment]
@pathboot the script is updated and working fine for me. Test it and give some feedback.
